#
#Wed Aug 15 16:57:08 CEST 2018
output..=target/classes/
bin.includes = META-INF/,\
               target/classes/,\
               target/dependency/snakeyaml.jar,\
               model/,\
               examples/,\
               YAML_FEATURE_MODELS.md,\
               plugin.xml,\
               plugin.properties
source..=src/,gen/
