/*
 * generated by Xtext 2.9.1
 */
package org.gravity.arte.testdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ARTELanguageStandaloneSetup extends ARTELanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new ARTELanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
