<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pm" nsURI="platform:/plugin/org.gravity.tgg.modisco.pm/model/Pm.ecore"
    nsPrefix="org.gravity.tgg.modisco.pm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.gravity.tgg.modisco"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="UnresolvedTypeDeclarationToTClass" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//UnresolvedTypeDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationFragmentToTFieldDefinition"
      eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//VariableDeclarationFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TFieldDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFieldNameToTField" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.modisco/model/Modisco.ecore#//MFieldName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifierToTFieldEntity" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Modifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TFieldDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMethodNameToTMethod" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.modisco/model/Modisco.ecore#//MMethodName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTNodeToTAnnotatable" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//ASTNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//annotations/TAnnotatable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFlowToTFlow" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.modisco/model/Modisco.ecore#//MFlow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassDeclarationToTClass" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//AnonymousClassDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifierToTClassEntity" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Modifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralToTNode" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//annotations/TAbstractNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineCommentToTTextAnnotation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//LineComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//annotations/TTextAnnotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifierToAbstractType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Modifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TAbstractType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSingleVariableAccessToTAccess" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.modisco/model/Modisco.ecore#//MSingleVariableAccess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TAccess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSyntethicMethodToTSyntethicMethod"
      eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.modisco/model/Modisco.ecore#//MSyntheticMethodDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TSyntethicMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValuePairToTAnnotationValue"
      eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//AnnotationMemberValuePair"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//annotations/TAnnotationValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelToTypeGraph" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TypeGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodInvocationToTAccess" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//AbstractMethodInvocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TAccess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDefinitionToTMember" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//BodyDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TMember"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSignatureToTSignature" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.modisco/model/Modisco.ecore#//MSignature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TSignature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MModifierToTModifier" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Modifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TModifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifierToTMethodEntity" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Modifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TMethodDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageToTPackage" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationToTAnnotation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Annotation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//annotations/TAnnotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldAccessToTAccess" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//FieldAccess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TAccess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeParameterToTClass" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//TypeParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticTypeToAccessStaticType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TCall"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeToTAbstractType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TAbstractType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEntryToTParameter" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.modisco/model/Modisco.ecore#//MEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAbstractFlowElementToTAbstractFlowElement"
      eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.modisco/model/Modisco.ecore#//MAbstractFlowElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/org.gravity.typegraph.basic/model/Basic.ecore#//TAbstractFlowElement"/>
  </eClassifiers>
  <eSubpackages name="Rules" nsURI="platform:/plugin/org.gravity.tgg.modisco.pm/model/Pm.ecore#//Rules"
      nsPrefix="Rules">
    <eClassifiers xsi:type="ecore:EClass" name="MemberInEnumVisibility" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassImplementsInterface_Abstract"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassTypeInterface" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeNested" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubPackageToPGPackage" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModelToPg" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeAccessOnAnnotation"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsChar" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInnerAnonClassMember" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinkDefinitionToType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInnerClassMember" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueArray" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PackageToPGPackage" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractAnnotationTypeAccess" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FieldName" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassTypeClass" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodParameterLink" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="InitializerInType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MemberInClassVisibility" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueStringArray"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FieldAccess" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodSignature" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceExtendsInterface" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueString" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceInAnonymous" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FlowNode" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType_Abstract" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassImplementsInterface" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberKey" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizedTypeToType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumInAnonymous" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsDouble" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="SuperMethodInvocation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodDefinition" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeAccessOnBodyDecl" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueBooleanArray"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsBoolean" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsInt" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConstructorInvocation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsShort" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeInAnonymous" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConstructorDefinition" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInAnonymous" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="NestedInterfaceInType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsFloat" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FieldDefinition" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="Initializer" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeInPackage" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClass" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FieldAccessReadWrite" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInnerMember" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceInPackage" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="InitializerInAnonymous" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodParameterLinkFirst" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueClass" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="NestedClassInType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataFlowOut" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypesIsVoid" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="TextAnnotations" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumConstant" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="SyntethicMethod" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeAccessOnSelf" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MemberInAnnotationVisibility" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="SuperConstructorInvocation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueBoolean" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinkDefinitionToAnonymous" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="NestedEnumInType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueNumber" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassExtendsClass" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassInAnonymous" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeMember" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsLong" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodInvocationTarget" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodDefinition" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassImplementsPatrameterizedInterface"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValue" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeNestedInType_Abstract" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationFragment" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodOverriding" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassInType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodName" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeInPackage_Abstract" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueAnnotation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueClassArray" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnresolvedMethodDeclaration" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInstanceCreation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeParameter" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnresolvedTypeDeclaration" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FieldAccessRead" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumInPackage" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayInitializerIgnoreExpressionsEdge"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodInvocationStaticType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodInvocation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodParameter" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FieldSignature" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeNestedInAnonymous_Abstract" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceMember" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypesOrphaned" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueAnnotationArray"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodInvocation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInPackage" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FieldAccessWrite" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataFlowIn" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValueNumberArray"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayTypeToType" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsByte" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypesVisibility" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
  </eSubpackages>
</ecore:EPackage>
