<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="refactoringgraph" nsURI="platform:/plugin/org.gravity.hulk.refactoringgraph/model/Refactoringgraph.ecore" nsPrefix="org.gravity.hulk.refactoringgraph">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.gravity.hulk"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="HMethodToDataClassAccess">
    <eSuperTypes href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric"/>
    <eOperations xsi:type="activities:MoflonEOperation" name="getRelativeAmount">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValue"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hDataClassSmell">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//codesmells/HDataClassSmell"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hDataClass">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tMethodDefinition">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HInBlobAccess">
    <eSuperTypes href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HBlobResolveAnnotation">
    <eSuperTypes href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hBlobAntiPattern">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//antipattern/HBlobAntiPattern"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hMoves" upperBound="-1" eType="//refactorings/HMoveMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hRefactorings" upperBound="-1" eType="//refactorings/HRefactoring"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HCluster">
    <eSuperTypes href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tMembers" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HInBlobClusterAccess">
    <eSuperTypes href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric"/>
    <eOperations xsi:type="activities:MoflonEOperation" name="getRelativeAmount">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValue"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hCluster" eType="//HCluster"/>
  </eClassifiers>
  <eSubpackages name="refactorings" nsURI="platform:/plugin/org.gravity.hulk.refactoringgraph/model/Refactoringgraph.ecore#//refactorings" nsPrefix="refactorings">
    <eClassifiers xsi:type="ecore:EClass" name="HRefactoring" abstract="true">
      <eSuperTypes href="platform:/plugin/org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HMoveMethod" eSuperTypes="//refactorings/HMoveMember"/>
    <eClassifiers xsi:type="ecore:EClass" name="HExtractClass" eSuperTypes="//refactorings/HRefactoring">
      <eOperations xsi:type="activities:MoflonEOperation" name="getAvgIba">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tMembers" upperBound="-1">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMember"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HMoveMember" abstract="true" eSuperTypes="//refactorings/HRefactoring">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="m2dc" lowerBound="1" eType="//HMethodToDataClassAccess"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iba" lowerBound="1" eType="//HInBlobAccess"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tSignature" upperBound="-1">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TSignature"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HMoveField" eSuperTypes="//refactorings/HMoveMember"/>
    <eClassifiers xsi:type="ecore:EClass" name="HMoveMembers" eSuperTypes="//refactorings/HRefactoring">
      <eStructuralFeatures xsi:type="ecore:EReference" name="hMoveMembers" upperBound="-1" eType="//refactorings/HMoveMember"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
