/*
 * generated by Xtext 2.9.1
 */
package org.gravity.arte.testdsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.gravity.arte.testdsl.arteLanguage.Test_File
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ARTELanguageInjectorProvider)
class ARTELanguageParsingTest{

	@Inject
	ParseHelper<Test_File> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
