<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basic" nsURI="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore"
    nsPrefix="org.gravity.typegraph.basic">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.gravity.typegraph"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tTarget" lowerBound="1"
        eType="#//TMember" eOpposite="#//TMember/accessedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tSource" lowerBound="1"
        eType="#//TMember" eOpposite="#//TMember/tAccessing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TAnnotatable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tAnnotation" upperBound="-1"
        eType="#//TAnnotation" containment="true" eOpposite="#//TAnnotation/tAnnotated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tAnnotated" lowerBound="1"
        eType="#//TAnnotatable" eOpposite="#//TAnnotatable/tAnnotation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TAnnotationType"
        eOpposite="#//TAnnotationType/annotations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TClass" eSuperTypes="#//TAbstractType">
    <eOperations xsi:type="activities:MoflonEOperation" name="getAllTMembers" eType="#//containers/TMemberContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentClass" eType="#//TClass"
        eOpposite="#//TClass/childClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childClasses" upperBound="-1"
        eType="#//TClass" eOpposite="#//TClass/parentClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
        eType="#//TInterface" eOpposite="#//TInterface/implementedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tClassEntity" lowerBound="1"
        eType="#//TClassEntity" eOpposite="#//TClassEntity/tClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
        eType="#//TFieldSignature" containment="true" eOpposite="#//TFieldSignature/field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pg" lowerBound="1" eType="#//TypeGraph"
        eOpposite="#//TypeGraph/fields"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFieldDefinition" eSuperTypes="#//TMember">
    <eOperations xsi:type="activities:MoflonEOperation" name="getSignatureString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        eType="#//TFieldSignature" eOpposite="#//TFieldSignature/definitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hiding" eType="#//TFieldDefinition"
        eOpposite="#//TFieldDefinition/hiddenBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hiddenBy" upperBound="-1"
        eType="#//TFieldDefinition" eOpposite="#//TFieldDefinition/hiding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tFieldEntity" lowerBound="1"
        eType="#//TFieldEntity" eOpposite="#//TFieldEntity/tFieldDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFieldSignature" eSuperTypes="#//TSignature">
    <eOperations xsi:type="activities:MoflonEOperation" name="getSignatureString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//TFieldDefinition" containment="true" eOpposite="#//TFieldDefinition/signature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="#//TField"
        eOpposite="#//TField/signatures"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TAbstractType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCall" eSuperTypes="#//TAccess"/>
  <eClassifiers xsi:type="ecore:EClass" name="TMember" abstract="true" eSuperTypes="#//TAnnotatable">
    <eOperations xsi:type="activities:MoflonEOperation" name="getSignature" eType="#//TSignature"/>
    <eOperations xsi:type="activities:MoflonEOperation" name="getSignatureString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definedBy" lowerBound="1"
        eType="#//TAbstractType" eOpposite="#//TAbstractType/defines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessedBy" upperBound="-1"
        eType="#//TAccess" eOpposite="#//TAccess/tTarget"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tAccessing" upperBound="-1"
        eType="#//TAccess" containment="true" eOpposite="#//TAccess/tSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pg" lowerBound="1" eType="#//TypeGraph"
        eOpposite="#//TypeGraph/methods"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
        eType="#//TMethodSignature" containment="true" eOpposite="#//TMethodSignature/method"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMethodDefinition" eSuperTypes="#//TMember">
    <eOperations xsi:type="activities:MoflonEOperation" name="getSignatureString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        eType="#//TMethodSignature" eOpposite="#//TMethodSignature/definitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overriding" eType="#//TMethodDefinition"
        eOpposite="#//TMethodDefinition/overriddenBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overriddenBy" upperBound="-1"
        eType="#//TMethodDefinition" eOpposite="#//TMethodDefinition/overriding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overloading" upperBound="-1"
        eType="#//TMethodDefinition" eOpposite="#//TMethodDefinition/overloadedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overloadedBy" upperBound="-1"
        eType="#//TMethodDefinition" eOpposite="#//TMethodDefinition/overloading"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//TAbstractType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tMethodEntity" lowerBound="1"
        eType="#//TMethodEntity" eOpposite="#//TMethodEntity/tMethodDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMethodSignature" eSuperTypes="#//TSignature">
    <eOperations xsi:type="activities:MoflonEOperation" name="getSignatureString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//TMethod" eOpposite="#//TMethod/signatures"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paramList" eType="#//TParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//TMethodDefinition" containment="true" eOpposite="#//TMethodDefinition/signature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//TAbstractType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TPackage" eSuperTypes="#//TAnnotatable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pg" eType="#//TypeGraph"
        eOpposite="#//TypeGraph/packages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpackage" upperBound="-1"
        eType="#//TPackage" containment="true" eOpposite="#//TPackage/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//TPackage"
        eOpposite="#//TPackage/subpackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//TClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//TInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTypes" upperBound="-1"
        eType="#//TAbstractType" eOpposite="#//TAbstractType/package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeGraph" lowerBound="1"
        eType="#//TypeGraph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//TParameter"
        eOpposite="#//TParameter/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//TParameter"
        eOpposite="#//TParameter/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TAbstractType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//TParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//TParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TSignature" abstract="true" eSuperTypes="#//TAnnotatable">
    <eOperations xsi:type="activities:MoflonEOperation" name="getSignatureString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//TPackage" containment="true" eOpposite="#//TPackage/pg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//TMethod" containment="true" eOpposite="#//TMethod/pg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//TField" containment="true" eOpposite="#//TField/pg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//TClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//TInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTypes" upperBound="-1"
        eType="#//TAbstractType" containment="true" eOpposite="#//TAbstractType/pg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tAnnotationTypes" upperBound="-1"
        eType="#//TAnnotationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tDeclaredEntities" upperBound="-1"
        eType="#//TDeclaredEntity" eOpposite="#//TDeclaredEntity/pg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TInterface" eSuperTypes="#//TAbstractType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedBy" upperBound="-1"
        eType="#//TClass" eOpposite="#//TClass/implements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentInterfaces" upperBound="-1"
        eType="#//TInterface" eOpposite="#//TInterface/childInterfaces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childInterfaces" upperBound="-1"
        eType="#//TInterface" eOpposite="#//TInterface/parentInterfaces"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TAbstractType" abstract="true" eSuperTypes="#//TAnnotatable">
    <eOperations xsi:type="activities:MoflonEOperation" name="getFullyQualifiedName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pg" lowerBound="1" eType="#//TypeGraph"
        eOpposite="#//TypeGraph/ownedTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//TPackage"
        eOpposite="#//TPackage/ownedTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" upperBound="-1"
        eType="#//TSignature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defines" upperBound="-1"
        eType="#//TMember" eOpposite="#//TMember/definedBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tLib" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TAnnotationType" eSuperTypes="#//TAbstractType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//TAnnotation" eOpposite="#//TAnnotation/type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TTextAnnotation" eSuperTypes="#//TAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TConstructorName" eSuperTypes="#//TMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="TConstructorSignature" eSuperTypes="#//TMethodSignature"/>
  <eClassifiers xsi:type="ecore:EClass" name="TConstructorDefinition" eSuperTypes="#//TMethodDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TRead" eSuperTypes="#//TAccess"/>
  <eClassifiers xsi:type="ecore:EClass" name="TWrite" eSuperTypes="#//TAccess"/>
  <eClassifiers xsi:type="ecore:EClass" name="TDeclaredEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pg" lowerBound="1" eType="#//TypeGraph"
        eOpposite="#//TypeGraph/tDeclaredEntities"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tVisibility" lowerBound="1"
        eType="#//TVisibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TClassEntity" eSuperTypes="#//TDeclaredEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tClass" lowerBound="1"
        eType="#//TClass" eOpposite="#//TClass/tClassEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFieldEntity" eSuperTypes="#//TDeclaredEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tFieldDefinition" lowerBound="1"
        eType="#//TFieldDefinition" eOpposite="#//TFieldDefinition/tFieldEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMethodEntity" eSuperTypes="#//TDeclaredEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tMethodDefinition" lowerBound="1"
        eType="#//TMethodDefinition" eOpposite="#//TMethodDefinition/tMethodEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TVisibility">
    <eLiterals name="TPrivate"/>
    <eLiterals name="TPackage" value="1"/>
    <eLiterals name="TProtected" value="2"/>
    <eLiterals name="TPublic" value="3"/>
  </eClassifiers>
  <eSubpackages name="containers" nsURI="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//containers"
      nsPrefix="containers">
    <eClassifiers xsi:type="ecore:EClass" name="TTypeContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tAbstractTypes" upperBound="-1"
          eType="#//TAbstractType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TAccessContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tAccessEdges" upperBound="-1"
          eType="#//TAccess"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TMemberContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tMembers" upperBound="-1"
          eType="#//TMember"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TClassContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tClass" upperBound="-1"
          eType="#//TClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TFieldContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tFields" upperBound="-1"
          eType="#//TField"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TFieldDefinitionContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tFieldDefinitions" upperBound="-1"
          eType="#//TFieldDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TFieldSignatureContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tFieldSignatures" upperBound="-1"
          eType="#//TFieldSignature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TSignatureContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tSignatures" upperBound="-1"
          eType="#//TSignature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TMethodDefinitionContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tMethodDefinitions" upperBound="-1"
          eType="#//TMethodDefinition"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
