<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hulk" nsURI="platform:/resource/org.gravity.hulk/model/Hulk.ecore"
    nsPrefix="org.gravity.hulk">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.gravity"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="HAntiPatternDetection" eSuperTypes="#//HAntiPatternHandling">
    <eOperations name="createAntiPatternDependencies">
      <eParameters name="graph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
    </eOperations>
    <eOperations name="createCodeSmellDependencies">
      <eParameters name="graph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
    </eOperations>
    <eOperations name="createMetricDependencies">
      <eParameters name="graph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
    </eOperations>
    <eOperations name="execute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getDependencyGraph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HAntiPatternResolving" eSuperTypes="#//HAntiPatternDetection">
    <eOperations name="createResolveCalculatorDependency">
      <eParameters name="graph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
    </eOperations>
    <eOperations name="getDependencyGraph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
    <eOperations name="execute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="createResolveAntiPatternDependency">
      <eParameters name="graph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
    </eOperations>
    <eOperations name="getSuperDependencyGraph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HDetector" abstract="true" eSuperTypes="Dfs.ecore#//Node">
    <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hAnnotation" upperBound="-1"
        eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hAntiPatternHandling" lowerBound="1"
        eType="#//HAntiPatternHandling" eOpposite="#//HAntiPatternHandling/hDetector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HAntiPatternHandling">
    <eOperations name="execute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getDependencyGraph" eType="ecore:EClass Dfs.ecore#//DFSGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hDetector" upperBound="-1"
        eType="#//HDetector" eOpposite="#//HDetector/hAntiPatternHandling"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="apg" lowerBound="1" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programlocation" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="detection" nsURI="platform:/resource/org.gravity.hulk/model/Hulk.ecore#//detection"
      nsPrefix="detection">
    <eClassifiers xsi:type="ecore:EClass" name="HCodeSmellDetector" abstract="true"
        eSuperTypes="#//HDetector"/>
    <eClassifiers xsi:type="ecore:EClass" name="HMetricCalculator" abstract="true"
        eSuperTypes="#//HDetector"/>
    <eClassifiers xsi:type="ecore:EClass" name="HAntiPatternDetector" abstract="true"
        eSuperTypes="#//HDetector"/>
    <eClassifiers xsi:type="ecore:EClass" name="HClassBasedCalculator" abstract="true"
        eSuperTypes="#//HDetector">
      <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
        <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
      </eOperations>
      <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="pg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HClassBasedMetricCalculator" abstract="true"
        eSuperTypes="#//detection/HClassBasedCalculator #//detection/HMetricCalculator">
      <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
        <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
      </eOperations>
      <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
        <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
      </eOperations>
      <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HRelativeDetector" abstract="true"
        eSuperTypes="#//HDetector">
      <eOperations name="calculateRelativeThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="level" eType="ecore:EEnum ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValueConstants"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="relative" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eSubpackages name="antipattern" nsURI="platform:/resource/org.gravity.hulk/model/Hulk.ecore#//detection/antipattern"
        nsPrefix="antipattern">
      <eClassifiers xsi:type="ecore:EClass" name="HBlobDetector" eSuperTypes="#//detection/HAntiPatternDetector #//detection/HClassBasedCalculator">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HGodClassDetector" eSuperTypes="#//detection/HAntiPatternDetector #//detection/HClassBasedCalculator">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HSwissArmyKnifeDetector" eSuperTypes="#//detection/HAntiPatternDetector #//detection/HClassBasedCalculator">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HSpaghettiCodeDetector" eSuperTypes="#//detection/HClassBasedCalculator #//detection/HAntiPatternDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="collect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="hAnnotation" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation"/>
        </eOperations>
        <eOperations name="connect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="hAntiPattern" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//antipattern/HSpaghettiCodeAntiPattern"/>
        </eOperations>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="codesmells" nsURI="platform:/resource/org.gravity.hulk/model/Hulk.ecore#//detection/codesmells"
        nsPrefix="codesmells">
      <eClassifiers xsi:type="ecore:EClass" name="HContollerClassDetector" eSuperTypes="#//detection/HCodeSmellDetector #//detection/HClassBasedCalculator #//detection/HRelativeDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateRelativeThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="level" eType="ecore:EEnum ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValueConstants"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HDataClassDetector" eSuperTypes="#//detection/HCodeSmellDetector #//detection/HClassBasedCalculator #//detection/HRelativeDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="makeChildDC">
          <eParameters name="tChild" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
          <eParameters name="tSmell" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//codesmells/HDataClassSmell"/>
        </eOperations>
        <eOperations name="calculateRelativeThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="level" eType="ecore:EEnum ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValueConstants"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HEmptyClassDetector" eSuperTypes="#//detection/HClassBasedCalculator #//detection/HCodeSmellDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HGetterSetterDetector" eSuperTypes="#//detection/HCodeSmellDetector #//detection/HClassBasedCalculator">
        <eOperations name="isGetterSetter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="method" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TMethodDefinition"/>
        </eOperations>
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HLargeClassLowCohesionDetector"
          eSuperTypes="#//detection/HClassBasedCalculator #//detection/HCodeSmellDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HLargeClassDetector" eSuperTypes="#//detection/HClassBasedCalculator #//detection/HCodeSmellDetector #//detection/HRelativeDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateRelativeThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="level" eType="ecore:EEnum ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValueConstants"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HLowCohesionDetector" eSuperTypes="#//detection/HClassBasedCalculator #//detection/HCodeSmellDetector #//detection/HRelativeDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateRelativeThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="level" eType="ecore:EEnum ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValueConstants"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HDataClassAccessorDetector" eSuperTypes="#//detection/HCodeSmellDetector #//detection/HClassBasedCalculator">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HManyParametersDetector" eSuperTypes="#//detection/HCodeSmellDetector #//detection/HClassBasedCalculator #//detection/HRelativeDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateRelativeThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="level" eType="ecore:EEnum ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValueConstants"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HMuchOverloadingDetector" eSuperTypes="#//detection/HCodeSmellDetector #//detection/HClassBasedCalculator #//detection/HRelativeDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateRelativeThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="level" eType="ecore:EEnum ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValueConstants"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HIntenseFieldUsageDetector" eSuperTypes="#//detection/HCodeSmellDetector #//detection/HClassBasedCalculator #//detection/HRelativeDetector">
        <eOperations name="calculate" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAnnotation">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateRelativeThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="level" eType="ecore:EEnum ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//values/HRelativeValueConstants"/>
        </eOperations>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="metrics" nsURI="platform:/resource/org.gravity.hulk/model/Hulk.ecore#//detection/metrics"
        nsPrefix="metrics">
      <eClassifiers xsi:type="ecore:EClass" name="HInvocationRelationCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateInvocValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="nii" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HIncommingInvocationMetric"/>
          <eParameters name="noi" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HOutgoingInvocationMetric"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HIGAMCalculator" eSuperTypes="#//detection/HMetricCalculator">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HNumberOfChildCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tParent" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HIGATCalculator" eSuperTypes="#//detection/HMetricCalculator">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HMemberNumberCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HLocalAccessRelationCalculator"
          eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="fa" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HLocalFieldAccessesMetric"/>
          <eParameters name="ma" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HLocalMethodAccessesMetric"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HMethodNumberCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HGetterSetterMethodRelationCalculator"
          eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="setter" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HSetterMetric"/>
          <eParameters name="getter" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HGetterMetric"/>
          <eParameters name="methods" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HNumberOfMethodsMetric"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HAverageParametersCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HAverageOverloadingInClassCalculator"
          eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HLocalMethodAccessCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HLocalFieldsAccessCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HFieldNumberCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HTotalVisibilityCalculator" eSuperTypes="#//detection/HMetricCalculator">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HTotalCouplingCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HLcom5Calculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="CalculateLcom5Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="nof" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HNumberOfFieldsMetric"/>
          <eParameters name="nom" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HNumberOfMethodsMetric"/>
          <eParameters name="lfa" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//metrics/HLocalFieldUniqueAccessMetric"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HLocalFieldUniqueAccessCalculator"
          eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HAfferentCouplingCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HEfferentCouplingCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HIncommingInvocationCalculator"
          eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HOutgoingInvocationCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HDepthOfInheritanceCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HGetterCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HSetterCalculator" eSuperTypes="#//detection/HClassBasedMetricCalculator">
        <eOperations name="calculateMetric" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HMetric">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="calculateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="resolve" nsURI="platform:/resource/org.gravity.hulk/model/Hulk.ecore#//resolve"
      nsPrefix="resolve">
    <eClassifiers xsi:type="ecore:EClass" name="HAntiPatternResolver" abstract="true"
        eSuperTypes="#//resolve/HResolver"/>
    <eClassifiers xsi:type="ecore:EClass" name="HResolver" abstract="true" eSuperTypes="#//HDetector"/>
    <eSubpackages name="calculators" nsURI="platform:/resource/org.gravity.hulk/model/Hulk.ecore#//resolve/calculators"
        nsPrefix="calculators">
      <eClassifiers xsi:type="ecore:EClass" name="HMethodToDataClassAccessCalculator"
          eSuperTypes="#//detection/HMetricCalculator #//resolve/HResolver">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
        <eOperations name="getAllAffectedMembers" upperBound="-1" eType="ecore:EClass ../../org.gravity.typegraph.basic/model/Basic.ecore#//TMember">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HInBlobAccessCalculator" eSuperTypes="#//detection/HMetricCalculator #//resolve/HResolver">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HClusterCalculator" eSuperTypes="#//resolve/HResolver">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
        </eOperations>
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HClusterAccessCalculator" eSuperTypes="#//resolve/HResolver">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="antipattern" nsURI="platform:/resource/org.gravity.hulk/model/Hulk.ecore#//resolve/antipattern"
        nsPrefix="antipattern">
      <eClassifiers xsi:type="ecore:EClass" name="HBlobResolver" eSuperTypes="#//detection/HAntiPatternDetector #//resolve/HAntiPatternResolver">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
        <eOperations name="isRefactoringPossible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="refactoring" eType="ecore:EClass ../../org.gravity.hulk.refactoringgraph/model/Refactoringgraph.ecore#//refactorings/HRefactoring"/>
        </eOperations>
        <eOperations name="createMove" eType="ecore:EClass ../../org.gravity.hulk.refactoringgraph/model/Refactoringgraph.ecore#//refactorings/HMoveMembers">
          <eParameters name="members" upperBound="-1" eType="ecore:EClass ../../org.gravity.typegraph.basic/model/Basic.ecore#//TMember"/>
          <eParameters name="source" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
          <eParameters name="target" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
          <eParameters name="parent" eType="ecore:EClass ../../org.gravity.hulk.refactoringgraph/model/Refactoringgraph.ecore#//HBlobResolveAnnotation"/>
        </eOperations>
        <eOperations name="allowedToTouch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="element" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//annotations/TAnnotatable"/>
        </eOperations>
        <eOperations name="init" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph">
          <eParameters name="pg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="executedMoves" upperBound="-1"
            eType="ecore:EClass ../../org.gravity.hulk.refactoringgraph/model/Refactoringgraph.ecore#//refactorings/HMoveMethod"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="original_apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="copy_apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HAlternativeBlobresolver" eSuperTypes="#//resolve/antipattern/HBlobResolver">
        <eOperations name="detect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="apg" eType="ecore:EClass ../../org.gravity.hulk.antipatterngraph/model/Antipatterngraph.ecore#//HAntiPatternGraph"/>
        </eOperations>
        <eOperations name="process" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="hCluster" eType="ecore:EClass ../../org.gravity.hulk.refactoringgraph/model/Refactoringgraph.ecore#//HInBlobClusterAccess"/>
          <eParameters name="tClass" eType="ecore:EClass http://www.gravity-tool.org/typegraph/basic#//TClass"/>
          <eParameters name="hParent" eType="ecore:EClass ../../org.gravity.hulk.refactoringgraph/model/Refactoringgraph.ecore#//HBlobResolveAnnotation"/>
        </eOperations>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
