<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modisco" nsURI="platform:/plugin/org.gravity.tgg.modisco/model/Modisco.pre.ecore" nsPrefix="org.gravity.tgg.modisco">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.gravity.tgg"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MFieldDefinitionToTFieldDefinition">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MFieldDefinition"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TFieldDefinition"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MConstructorDefinitionToTParameterList">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MConstructorDefinition"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TParameterList"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclarationToTClass">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//ClassDeclaration"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnitToTypeGraph">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//CompilationUnit"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TypeGraph"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageToTPackage">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Package"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TPackage"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelToTypeGraph">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Model"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TypeGraph"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMethodDefinitionToTMethodDefinition">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MMethodDefinition"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMethodDefinition"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationFragmentToTFieldDefinition">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//VariableDeclarationFragment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TFieldDefinition"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodInvocationToTAccess">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//AbstractMethodInvocation"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TAccess"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceDeclarationToTInterface">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//InterfaceDeclaration"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TInterface"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDefinitionToTMember">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MDefinition"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldAccessToTAccess">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//FieldAccess"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TAccess"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeToTClass">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//PrimitiveType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassDeclarationToTClass">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//AnonymousClassDeclaration"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMethodNameToTMethod">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MMethodName"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMethod"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMethodSignatureToTMethodSignature">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MMethodSignature"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMethodSignature"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMethodSignatureToTParameterList">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MMethodSignature"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TParameterList"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEntryToTParameter">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MEntry"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TParameter"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockToTMethodDefinition">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Block"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMethodDefinition"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSignatureToTSignature">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MSignature"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TSignature"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFieldSignatureToTFieldSignature">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MFieldSignature"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TFieldSignature"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyDeclarationToTAnnotatable">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//BodyDeclaration"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TAnnotatable"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeToTAbstractType">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Type"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TAbstractType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFieldNameToTField">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MFieldName"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TField"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineCommentToTTextAnnotation">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//LineComment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TTextAnnotation"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSignatureToTMethodSignature">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMethodSignature"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.modisco/model/Modisco.ecore#//MSignature"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleVariableAccessToTAccess">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TAccess"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//SingleVariableAccess"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorDeclarationToTMethodDefinition">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//ConstructorDeclaration"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMethodDefinition"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationToTAnnotation">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//Annotation"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TAnnotation"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorDeclarationToTMethod">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//ConstructorDeclaration"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMethod"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorDeclarationToTMethodSignature">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//ConstructorDeclaration"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TMethodSignature"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeParameterToTClass">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//TypeParameter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnresolvedTypeDeclarationToTClass">
    <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/MoDisco/Java/0.2.incubation/java#//UnresolvedTypeDeclaration"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.gravity.typegraph.basic/model/Basic.ecore#//TClass"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="Rules" nsURI="platform:/plugin/org.gravity.tgg.modisco/model/Modisco.pre.ecore#//Rules" nsPrefix="Rules">
    <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodDefinitionBloc">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelToPg">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PackageToPGPackage">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubPackageToPGPackage">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Types" abstract="true">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NestedInterfaceInType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizedTypeToClass">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NestedClassInType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SignatureReturnType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldSignature">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractMethodInvocation" abstract="true">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkDefinitionToAnonymous">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypesToClass" abstract="true">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodParameterType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NestedTypes" abstract="true">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldAccess">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceExtendsInterface">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassExtendsClass">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassImplementsInterface">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInnerMember">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationFragment">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldName">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldDefinition">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkDefinitionToType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextAnnotations">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NestedAnnotationType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeWithValue">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsInt">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClass">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodParameterLinkFirst">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodSignature">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayTypeToClass">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsBoolean">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsChar">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsByte">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsShort">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsLong">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsFloat">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeIsDouble">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodDefinition">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Annotatio">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NestedEnum">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypesIsVoid">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodParameterLink">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodName">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkSignatureToType">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodParameter">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enum">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationSetID">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodInvocation">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperMethodInvocation">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstructorInvocation">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperConstructorInvocation">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NestedTypesinAnonymous" abstract="true">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeParameter">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodOverriding">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constructor">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnresolvedTypeDeclaration">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInAnonymous">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumInAnonymous">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceInAnonymous">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeInAnonymous">
      <eSuperTypes href="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
