name: Java CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository with submodules
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        ssh-key: ${{ secrets.SECPL_PULL_KEY }}
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'  
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn clean verify sonar:sonar -Pcoverage -Declipse.p2.mirrors=false -Dsonar.projectKey=gravity -Dsonar.login=${{secrets.SONAR_LOGIN}}
    - name: Publisch Pre-Release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          build/org.gravity.updatesite/target/site.zip
          build/org.gravity.headless.product/target/products/*.zip
    - name: Publisch Release
      if: ${{ github.ref_type == 'tag' }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          build/org.gravity.updatesite/target/site.zip
          build/org.gravity.headless.product/target/products/*.zip
