name: Java CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository with submodules
      uses: actions/checkout@v4
      with: 
#        ssh-key: ${{ secrets.SECPL_PULL_KEY }}
        submodules: 'recursive'
        fetch-depth: 0
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.10.0
      with:
          java-version: 21
    - name: Run headless test   
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: xvfb-run mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Declipse.p2.mirrors=false
    - name: Publisch Pre-Release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          build/org.gravity.updatesite/target/site.zip
          build/org.gravity.headless.product/target/products/*.zip
    - name: Publish Release
      if: ${{ github.ref_type == 'tag' }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          build/org.gravity.updatesite/target/site.zip
          build/org.gravity.headless.product/target/products/*.zip

